CONSUMER_KEY = 'YOU HAVE TO PUT YOUR CONSUMER_KEY'
CONSUMER_SECRET = 'YOU HAVE TO PUT YOUR CONSUMER_SECRET'
ACCESS_TOKEN = 'YOU HAVE TO PUT YOUR ACCESS_TOKEN'
ACCESS_SECRET = 'YOU HAVE TO PUT YOUR ACCESS_SECRET'